name: Test

on:
  push:
    branches: ['main']

jobs:

    runs-on: ubuntu-latest


  test:
    runs-on: ubuntu-latest 
    env:
      MONGO: mongodb://localhost:27017

    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          mongodb-version: ['4.2', '4.4', '5.0', '6.0']
          cache: 'npm'
          - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.8.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run componenttest