name: Componenttest
on:
  push:
    branches: [ "main" ]
  

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      MONGO: mongodb://localhost:27017

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        mongodb-version: ['4.2', '4.4', '5.0', '6.0']

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
        mongodb-version: ${{ matrix.mongodb-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run componenttest
      - run: npm run  integrationtest


  notify:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Discord tests notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

        uses: Ilshidur/action-discord@0.3.2
        with:
          args: 'A new commit has been pushed to Grupp-3-Backend repository. Tests are passed'


  deploy:
    needs: notify
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          branch: 'main'
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'grupp-3-backend'
          heroku_email: ${{secrets.HEROKU_EMAIL}} 
    
  deployment-notify:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

        uses: Ilshidur/action-discord@0.3.2
        with:
          args: 'App has been successfully deployed'
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@0.3.
